AWSTemplateFormatVersion: 2010-09-09

Description: "データベース"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "DB Configuration"
        Parameters:
          - RDSMasterUsername
          - RDSMasterUserPassword
          - RDSInstanceType        

Parameters:
  RDSMasterUsername:
    Type: String
    Default: admin

  RDSMasterUserPassword:
    Type: String
    NoEcho: true

  RDSInstanceType:
    Type: String
    Default: db.t2.micro  



Resources:
  

  # データベースの作成
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: !Ref RDSInstanceType
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 7 
      DBName: Test_Database  
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      Engine: mysql 
      EngineVersion: 5.7.34
      MasterUsername: !Ref RDSMasterUsername
      MasterUserPassword: !Ref RDSMasterUserPassword
      MultiAZ: true 
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue RDSSecurityGroup

         
       
  # サブネットグループ
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test
      SubnetIds:
        - !ImportValue PublicSubnet3
        - !ImportValue PublicSubnet4        
